# Setup
title:            Tiz314
tagline:          'CyberSec student'
description:      'Reverse Engineering, Embedded systems and network protocols analysis'
url:              "https://github.com/tiz314" 
baseurl:          ""

author:
  name:           'Tiz314'

markdown: kramdown
highlighter: rouge
permalink: pretty

paginate: 5

remote_theme: poole/hyde

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
