# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: K!nd4SUS

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
minima:
  skin:  dark
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/K1nd4SUS/"
    - title: X
      icon: x-twitter
      url: "https://x.com/k1nd4sus_ctf"
  

  #social_links:
  #  - title: Minima Theme repository at GitHub
  #    icon: github
  #    url: "https://github.com/jekyll/minima"
  #  - title: Jekyll at X (formerly Twitter)
  #    icon: x-twitter
  #    url: "https://x.com/jekyllrb"

description: Università degli Studi di Milano

author:
  name: "powered by [kuom]"
  email: >-

header_pages:
  - about.markdown
  - blog.markdown
  - ctf.markdown
  - milan0day.markdown
  - contatti.markdown
  - statuto.markdown
  - regolamento.markdown
  - organigramma.markdown
  - faq.markdown

collections:
  authors:
    output: true
    permalink: author/:title/

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
