# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column Jekyll theme that pairs a prominent sidebar with uncomplicated content.'
url:              "https://your-username.github.io" # Change to your actual GitHub Pages URL
baseurl:          "" # Leave blank for user/organization site

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

paginate: 5

# Remote theme (requires jekyll-remote-theme plugin)
remote_theme: poole/hyde

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
